/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_iceCream: THREE.Mesh;
    Mesh_iceCream_1: THREE.Mesh;
  };
  materials: {
    purpleLight: THREE.MeshStandardMaterial;
    brownLight: THREE.MeshStandardMaterial;
  };
};

export function IceCreamModel(props: JSX.IntrinsicElements["group"]) {
  const group = useRef();

  // @ts-ignore
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/ice-cream/model.gltf"
  ) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_iceCream.geometry}
        material={materials.purpleLight}
      />
      <mesh
        geometry={nodes.Mesh_iceCream_1.geometry}
        material={materials.brownLight}
      />
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/ice-cream/model.gltf"
);
