/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export function SwordModel(props: GroupProps) {
  const group = useRef();
  // @ts-ignore
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/sword-1/model.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.5} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cube4214.geometry}
          material={materials["Metal.102"]}
        />
        <mesh
          geometry={nodes.Cube4214_1.geometry}
          material={materials["BrownDark.073"]}
        />
        <mesh
          geometry={nodes.Cube4214_2.geometry}
          material={materials["Stone.037"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/sword-1/model.gltf"
);
