/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Cube4214: THREE.Mesh;
    Cube4214_1: THREE.Mesh;
    Cube4214_2: THREE.Mesh;
  };
  materials: {
    ["Metal.102"]: THREE.MeshStandardMaterial;
    ["BrownDark.073"]: THREE.MeshStandardMaterial;
    ["Stone.037"]: THREE.MeshStandardMaterial;
  };
};

export function SwordModel(props: JSX.IntrinsicElements["group"]) {
  const group = useRef();

  // @ts-ignore
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/sword-1/model.gltf"
  ) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Cube4214.geometry}
          material={materials["Metal.102"]}
        />
        <mesh
          geometry={nodes.Cube4214_1.geometry}
          material={materials["BrownDark.073"]}
        />
        <mesh
          geometry={nodes.Cube4214_2.geometry}
          material={materials["Stone.037"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/sword-1/model.gltf"
);
