/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_wholerHam: THREE.Mesh;
    Mesh_wholerHam_1: THREE.Mesh;
  };
  materials: {
    brownDark: THREE.MeshStandardMaterial;
    brownLight: THREE.MeshStandardMaterial;
  };
};

export function WholerHamModel(props: JSX.IntrinsicElements["group"]) {
  const group = useRef();

  // @ts-ignore
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/wholer-ham/model.gltf"
  ) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.77}>
        <mesh
          geometry={nodes.Mesh_wholerHam.geometry}
          material={materials.brownDark}
        />
        <mesh
          geometry={nodes.Mesh_wholerHam_1.geometry}
          material={materials.brownLight}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/wholer-ham/model.gltf"
);
