/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export function WholerHamModel(props: GroupProps) {
  const group = useRef();
  // @ts-ignore
  const { nodes, materials } = useGLTF(
    "https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/wholer-ham/model.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.77}>
        <mesh
          geometry={nodes.Mesh_wholerHam.geometry}
          material={materials.brownDark}
        />
        <mesh
          geometry={nodes.Mesh_wholerHam_1.geometry}
          material={materials.brownLight}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/wholer-ham/model.gltf"
);
